#ifndef REVERSETYPINGGAME_GLOBAL_H
#define REVERSETYPINGGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REVERSETYPINGGAME_LIBRARY)
#define REVERSETYPINGGAME_EXPORT Q_DECL_EXPORT
#else
#define REVERSETYPINGGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // REVERSETYPINGGAME_GLOBAL_H
