#ifndef SIMONSAYSGAME_GLOBAL_H
#define SIMONSAYSGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMONSAYSGAME_LIBRARY)
#define SIMONSAYSGAME_EXPORT Q_DECL_EXPORT
#else
#define SIMONSAYSGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMONSAYSGAME_GLOBAL_H
