#ifndef REACTIONCLICKGAME_GLOBAL_H
#define REACTIONCLICKGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REACTIONCLICKGAME_LIBRARY)
#define REACTIONCLICKGAME_EXPORT Q_DECL_EXPORT
#else
#define REACTIONCLICKGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // REACTIONCLICKGAME_GLOBAL_H
