#ifndef TYPINGSPEEDGAME_GLOBAL_H
#define TYPINGSPEEDGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TYPINGSPEEDGAME_LIBRARY)
#define TYPINGSPEEDGAME_EXPORT Q_DECL_EXPORT
#else
#define TYPINGSPEEDGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // TYPINGSPEEDGAME_GLOBAL_H
