#ifndef STROOPEFFECTGAME_GLOBAL_H
#define STROOPEFFECTGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STROOPEFFECTGAME_LIBRARY)
#define STROOPEFFECTGAME_EXPORT Q_DECL_EXPORT
#else
#define STROOPEFFECTGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // STROOPEFFECTGAME_GLOBAL_H
