#ifndef DIGITSPANTEST_GLOBAL_H
#define DIGITSPANTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DIGITSPANTEST_LIBRARY)
#define DIGITSPANTEST_EXPORT Q_DECL_EXPORT
#else
#define DIGITSPANTEST_EXPORT Q_DECL_IMPORT
#endif

#endif // DIGITSPANTEST_GLOBAL_H
