#ifndef CIRCLEHOLDGAME_GLOBAL_H
#define CIRCLEHOLDGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CIRCLEHOLDGAME_LIBRARY)
#define CIRCLEHOLDGAME_EXPORT Q_DECL_EXPORT
#else
#define CIRCLEHOLDGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // CIRCLEHOLDGAME_GLOBAL_H
