#ifndef REACTIONTRAINER_GLOBAL_H
#define REACTIONTRAINER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REACTIONTRAINER_LIBRARY)
#define REACTIONTRAINER_EXPORT Q_DECL_EXPORT
#else
#define REACTIONTRAINER_EXPORT Q_DECL_IMPORT
#endif

#endif // REACTIONTRAINER_GLOBAL_H
