#ifndef TRAILMAKINGTEST_GLOBAL_H
#define TRAILMAKINGTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRAILMAKINGTEST_LIBRARY)
#define TRAILMAKINGTEST_EXPORT Q_DECL_EXPORT
#else
#define TRAILMAKINGTEST_EXPORT Q_DECL_IMPORT
#endif

#endif // TRAILMAKINGTEST_GLOBAL_H
