#ifndef ARROWSEQUENCEGAME_GLOBAL_H
#define ARROWSEQUENCEGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ARROWSEQUENCEGAME_LIBRARY)
#define ARROWSEQUENCEGAME_EXPORT Q_DECL_EXPORT
#else
#define ARROWSEQUENCEGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // ARROWSEQUENCEGAME_GLOBAL_H
