#ifndef CIRCLECLICKGAME_GLOBAL_H
#define CIRCLECLICKGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CIRCLECLICKGAME_LIBRARY)
#define CIRCLECLICKGAME_EXPORT Q_DECL_EXPORT
#else
#define CIRCLECLICKGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // CIRCLECLICKGAME_GLOBAL_H
