#ifndef RESTORESEQUENCEGAME_GLOBAL_H
#define RESTORESEQUENCEGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RESTORESEQUENCEGAME_LIBRARY)
#define RESTORESEQUENCEGAME_EXPORT Q_DECL_EXPORT
#else
#define RESTORESEQUENCEGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // RESTORESEQUENCEGAME_GLOBAL_H
