#ifndef FINDANOTHERCOLORGAME_GLOBAL_H
#define FINDANOTHERCOLORGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FINDANOTHERCOLORGAME_LIBRARY)
#define FINDANOTHERCOLORGAME_EXPORT Q_DECL_EXPORT
#else
#define FINDANOTHERCOLORGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // FINDANOTHERCOLORGAME_GLOBAL_H
