#ifndef CIRCLEGAME_GLOBAL_H
#define CIRCLEGAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CIRCLEGAME_LIBRARY)
#define CIRCLEGAME_EXPORT Q_DECL_EXPORT
#else
#define CIRCLEGAME_EXPORT Q_DECL_IMPORT
#endif

#endif // CIRCLEGAME_GLOBAL_H
